### ISSUE TITLE
Rayo fax: specifying headers

### ISSUE THREAD

**Issue by crienzo** [rayo/xmpp#83]
We need to be able to specify identity and header for transmitted faxes:

identity: telephone number (spaces, digits, +)
header: header line at top of each page

**Comment by benlangfeld** [comment]
So this (along with #84) are difficult because the output component's `<document/>` element is not flexible enough. We can't add children to it because those would be considered to _be_ the document as inline data.

Three possible solutions:
1. Use some funky URL format like: `http://example.com/my_fax.tiff?pages=2..4&identity=+140455555555&header=This%20is%20some%20header`
2. Allow something like
   
   ``` xml
   <output>
     <fax url="http://example.com/my_fax.tiff" pages="2..4" identity..../>
   </output>
   ```
3. Specify some document format for fax like so:
   
   ``` xml
   <output>
     <document content-type="something">
       <url>http://example.com/my_fax.tiff</url>
       <identity>BLAH</identity>
     </document>
   </output>
   ```

I think I prefer option 2. Thoughts?

**Comment by crienzo** [comment]
option 2 is fine with me.
